### PR TITLE
Fix flaky MigratedDataTest API-1243

### LINKED ISSUE #646: Flaky MigratedDataTest [API-1243]
`MigratedDataTest` got flaky for some reasons. See http://jenkins.hazelcast.com/job/NodeJS-pr-builder/647/testReport/junit/(root)/killing%20a%20server%20migrates%20data%20to%20the%20other%20node,%20migrated%20data%20has%20new%20uuid,%20near%20cache%20discards%20data%20with%20old%20uuid/MigratedDataTest_killing_a_server_migrates_data_to_the_other_node__migrated_data_has_new_uuid__near_cache_discards_data_with_old_uuid/ as an example

### PR DESCRIPTION
**Pull request by srknzl**
Fixes the flaky test. I increased the timeout as the fix. Also did small refactoring.

fixes #646

### CODE REVIEW

**Review by yuce — APPROVED** [review]

File: test/integration/backward_compatible/parallel/nearcache/MigratedDataTest.js [hunk 1]
```diff
@@ -42,21 +42,22 @@ describe('MigratedDataTest', function () {
...
         }
-        checkPartitionTable(10);
+        checkPartitionTable(600);
         return deferred.promise;
     }
 
     async function waitUntilPartitionMovesTo(partitionService, partitionId, uuid) {
         const deferred = deferredPromise();
-        (function resolveOrTimeout(remainingTries) {
+        function resolveOrTimeout(remainingTries) {
```
Comment (mdumandag) [inline test/integration/backward_compatible/parallel/nearcache/MigratedDataTest.js:51]: Minor: maybe as a simplification, we can get rid of the recursive function calls and replace it with a simple for loop. The same holds true for `waitForPartitionTableEvent`

Comment (srknzl) [reply test/integration/backward_compatible/parallel/nearcache/MigratedDataTest.js:51]: We can do that but I did not want to spend time on these

**Review by mdumandag — APPROVED** [review]
