### PR TITLE
Fix flaky HazelcastClientTest API-1194 [4.1.x]

### LINKED ISSUE #1173: getDistributedObjects - "getDistributedObjects does not return removed object" failure  [API-1194]
Failed on Node 10 and 17, on windows with commit https://github.com/hazelcast/hazelcast-nodejs-client/commit/e6956513c7e97995cf997172cf6a5ab15be8cd87

```
1) HazelcastClientTest[smart=false]
       getDistributedObjects does not return removed object:
     Error: Rejected due to timeout of 5000ms
      at Timeout.setTimeout (test\TestUtil.js:86:20)
```

### PR DESCRIPTION
**Pull request by srknzl**
Fixes the possible flakiness of the test and makes the test cleaner. 

fixes #1173

### CODE REVIEW

File: test/integration/HazelcastClientTest.js [hunk 1]
```diff
@@ -114,44 +93,33 @@ configParams.forEach(function (cfg) {
...
-                        } catch (e) {
-                            done(e);
-                        }
-                    });
+        it('getDistributedObjects does not return removed object', async function () {
+            managed.addObject(await client.getMap('map1'));
+            managed.addObject(await client.getMap('map2'));
+            managed.addObject(await client.getMap('map3'));
+
+
```
Comment (mdumandag) [inline test/integration/HazelcastClientTest.js:114]: minor: unnecessary newline

**Review by mdumandag — APPROVED** [review]

**Review by mdumandag — APPROVED** [review]

**Review by yuce — APPROVED** [review]
