### PR TITLE
Fix client resource leak on failed start

### LINKED ISSUE #687: Client does not clean up resources on failed start
If one of client start steps fails, there may be active background tasks left, like `HeartbeatManager.task` or `Statistics.task`. The client should stop all scheduled tasks on a failed start.

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Closes #687

Client was not stopping internal periodical tasks on failed start. As a result, those tasks kept working and the whole client instance was leaking. At least three client instances were leaking in our test suite.

### CODE REVIEW

File: src/HazelcastClient.ts [hunk 1]
```diff
@@ -469,7 +469,11 @@ export class HazelcastClient {
                 return this;
             })
             .catch((e) => {
-                logger.error('HazelcastClient', 'Client failed to start', e);
+                this.shutdown()
```
Comment (mdumandag) [inline src/HazelcastClient.ts:472]: Should we wait for this shutdown call before throwing immediately?

File: test/ClientProxyTest.js [hunk 2]
```diff
@@ -52,9 +52,9 @@ describe('ClientProxyTest', function () {
         assert.equal(mapProxy.getConnectedServerVersion(), -1);
     });
 
-    it('Client with a 3.7 server connection should return the version', function () {
+    it('client with a 4.7 server connection should return the version', function () {
```
Comment (mdumandag) [inline test/ClientProxyTest.js:55]: Minor: `4.7 server` -> `4.1 server`

Comment (puzpuzpuz) [reply test/ClientProxyTest.js]: Fixed. Thanks for spotting this.

File: src/HazelcastClient.ts (hunk 1 above)
Comment (puzpuzpuz) [reply src/HazelcastClient.ts:472]: There are two reasons why I implemented the shutdown-on-start-error in "async" way. First, `shutdown` call itself might take some time to finish. Second, `shutdown` may throw (reject to be more precise) and shadow the original error. It's possible to mitigate the at least the second problem, but I'm not sure if it's worth it. Do you see any benefit for the end user in "sync" approach?

**Comment by puzpuzpuz** [comment]
verify

File: src/HazelcastClient.ts (hunk 1 above)
Comment (mdumandag) [reply src/HazelcastClient.ts:472]: Well, at first I thought the shutdown call should be a quick one. I thought the only thing that could take some time is the shutdown call of the connection manager. If it is possible for this to take some time, then it makes sense to keep things as it is.

Comment (puzpuzpuz) [reply src/HazelcastClient.ts:472]: Yes, `CPSubsystem` may take some time to release sessions.

Comment (mdumandag) [reply src/HazelcastClient.ts:472]: But, there should not be any sessions created during the startup

Comment (puzpuzpuz) [reply src/HazelcastClient.ts:472]: Yes, I forgot to mention that the session clean up scenario is not currently possible, but that may change in future versions, as `shutdown` is async since 4.0.

**Review by mdumandag — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@mdumandag thanks for the review!

**Comment by puzpuzpuz** [comment]
Failed test is a known flaky test: #616

**Review by mdumandag — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
verify

**Comment by puzpuzpuz** [comment]
verify
