### PR TITLE
Isolate failing near cache test API-1161

### LINKED ISSUE #1176: NearCachedMapTest test fail [API-1161]
failed with node 10.24.1, on windows, client commit 8ad6e6b846e2c1b79e1d46534386562cda422d7b

```
1) NearCachedMapTest
       invalidate on change=true
         get returns null if the entry was removed by another client:

      AssertionError: expected 1 to equal 0
      + expected - actual

      -1
      +0
      
      at expectStats (test\integration\backward_compatible\parallel\map\NearCachedMapTest.js:71:43)
      at Context.<anonymous> (test\integration\backward_compatible\parallel\map\NearCachedMapTest.js:106:17)
```

can easily reproduce on another setup such as node 16 and macos.

### PR DESCRIPTION
**Pull request by srknzl**
I think the test logic is correct. I ran the test on its own several times and could not get a fail. https://github.com/srknzl/hazelcast-nodejs-client/actions/runs/1880356435/attempts/1  (You can see all attempts in the attempts selector.)

I think isolating the test can fix the flakiness. To do that, I create a client before each test.

fixes #1176

### CODE REVIEW

File: test/integration/backward_compatible/parallel/map/NearCachedMapTest.js [hunk 1]
```diff
@@ -103,6 +103,7 @@ describe('NearCachedMapTest', function () {
                 }
 
                 await map1.get('key1');
+                expect(getNearCacheStats(map1).missCount).to.be.eq(1);
```
Comment (srknzl) [inline test/integration/backward_compatible/parallel/map/NearCachedMapTest.js:106]: This is a required precondition for the assertion in `assertTrueEventually` to be valid. I added it here to be sure this assertion holds.

File: test/integration/backward_compatible/parallel/sql/DataTypeTest.js [hunk 2]
```diff
@@ -822,7 +822,7 @@ describe('Data type test', function () {
             // JSON support is added in 5.1.
             TestUtil.markClientVersionAtLeast(this, '5.1');
             TestUtil.markServerVersionAtLeast(this, client, '5.1');
-
```
Comment (srknzl) [inline test/integration/backward_compatible/parallel/sql/DataTypeTest.js:825]: Somehow leftover traling space that I removed as per eslint warning.

**Review by yuce — APPROVED** [review]

**Review by mdumandag — APPROVED** [review]
