### PR TITLE
Nested compact field's serializer can be None if it is not registered [API-1415]

### LINKED ISSUE #1323: API-1415 Nested compact field's serializer can be undefined if it is not registered
Error:
```
TypeError: Cannot read property 'getClass' of undefined
    at CompactStreamSerializer.writeObject (/home/serkan/forked/hazelcast-nodejs-client/lib/serialization/compact/CompactStreamSerializer.js:104:41)
    at /home/serkan/forked/hazelcast-nodejs-client/lib/serialization/compact/DefaultCompactWriter.js:103:36
    at DefaultCompactWriter.writeVariableSizeField (/home/serkan/forked/hazelcast-nodejs-client/lib/serialization/compact/DefaultCompactWriter.js:278:13)
    at DefaultCompactWriter.writeCompact (/home/serkan/forked/hazelcast-nodejs-client/lib/serialization/compact/DefaultCompactWriter.js:102:21)
    at MainDTOSerializer.write (/home/serkan/forked/hazelcast-nodejs-client/test/integration/backward_compatible/parallel/serialization/compact/CompactUtil.js:1295:20)
    at CompactStreamSerializer.writeSchemaAndObject (/home/serkan/forked/hazelcast-nodejs-client/lib/serialization/compact/CompactStreamSerializer.js:99:27)
    at CompactStreamSerializer.writeObject (/home/serkan/forked/hazelcast-nodejs-client/lib/serialization/compact/CompactStreamSerializer.js:112:14)
    at CompactStreamSerializer.write (/home/serkan/forked/hazelcast-nodejs-client/lib/serialization/compact/CompactStreamSerializer.js:69:18)
    at SerializationServiceV1.toData (/home/serkan/forked/hazelcast-nodejs-client/lib/serialization/SerializationService.js:82:20)
    at MapProxy.toData (/home/serkan/forked/hazelcast-nodejs-client/lib/proxy/BaseProxy.js:129:42)
```

To reproduce:

Put the following file in `test/unit/serialization/compact` and run it. Since InnerDTO is a nested compact CompactStreamSerializer is used without [checking](https://github.com/hazelcast/hazelcast-nodejs-client/blob/aceb3fc6f76d27f5e47176fe2e1c5e5b8f1d5423/src/serialization/SerializationService.ts#L285) if it is compact serializable or not, and `serializer` variable [here](https://github.com/hazelcast/hazelcast-nodejs-client/blob/aceb3fc6f76d27f5e47176fe2e1c5e5b8f1d5423/src/serialization/compact/CompactStreamSerializer.ts#L141) becomes undefined. As a fix, we should check if there is a serializer explicitly before that line. 

```js
'use strict';
const {Client} = require('../../../../lib');
const {
    createMainDTO,
    MainDTOSerializer,
    NamedDTOSerializer,
} = require('../../../integration/backward_compatible/parallel/serialization/compact/CompactUtil');


async function main() {
    const serializers = [new MainDTOSerializer(), new NamedDTOSerializer()];
    const client = await Client.newHazelcastClient({
        serialization: {
            compact: {
                serializers
            }
        }
    });

    const map = await client.getMap('test');
    const mainDTO = createMainDTO();
    await map.set('1', mainDTO);
    console.log((await map.get('1')));
    await client.shutdown();
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
```

### PR DESCRIPTION
**Pull request by mehmettokgoz**
Fixes #1323  

- Added check for `undefined` serializer before calling `getClass()` on it, throw a `HazelcastSerializationError` in this case.
- Added a new test for missing nested serializer case, it checks if a `HazelcastSerializationError` has been thrown.
- Change the `serialize()` method to prevent an infinite loop in case of a missing serializer.

### CODE REVIEW

File: src/serialization/compact/CompactStreamSerializer.ts [hunk 1]
```diff
@@ -138,6 +139,9 @@ export class CompactStreamSerializer {
 
     writeObject(output: PositionalObjectDataOutput, obj: any) : void {
         const compactSerializer = this.classToSerializerMap.get(obj.constructor);
+        if (compactSerializer == undefined) {
+            throw new HazelcastSerializationError(`No serializer is registered for class ${obj.constructor.name}.`)
```
Comment (srknzl) [inline src/serialization/compact/CompactStreamSerializer.ts:143]: I think we can do the following change since constructor functions can be used with compact:
```suggestion
            throw new HazelcastSerializationError(`No serializer is registered for class/constructor ${obj.constructor.name}.`)
```

File: test/integration/backward_compatible/parallel/serialization/compact/CompactUtil.js [hunk 2]
```diff
@@ -1486,6 +1487,8 @@ if (TestUtil.isClientVersionAtLeast('5.1.0')) {
         } catch (e) {
             if (e instanceof SchemaNotReplicatedError) {
                 await schemaService.put(e.schema);
+            } else if (e instanceof HazelcastSerializationError) {
+                throw new HazelcastSerializationError(e.message, e.cause, e.serverStackTrace);
```
Comment (srknzl) [inline test/integration/backward_compatible/parallel/serialization/compact/CompactUtil.js:1491]: This code is not needed. any reasoning? You are catching and rethrowing the same exception.

File: test/unit/serialization/compact/CompactTest.js [hunk 3]
```diff
@@ -244,4 +246,18 @@ describe('CompactTest', function () {
         const object = await serializationService.toObject(data);
         object.should.be.deep.equal(employer);
     });
+
+    it('should not serialize without nested fields serializer', async function() {
```
Comment (srknzl) [inline test/unit/serialization/compact/CompactTest.js:250]:
```suggestion
    it('should throw proper error when nested field serializer is missing', async function() {
```

Comment (srknzl) [reply test/unit/serialization/compact/CompactTest.js:250]: The main problem was throwing TypeError in an internal code of the Node.js client. Now we handle it and throw a proper messaged error. Hence the name suggestion.

File: test/unit/serialization/compact/CompactTest.js [hunk 4]
```diff
@@ -244,4 +246,18 @@ describe('CompactTest', function () {
...
+        const bundle = createSerializationService(
+            [new MainDTOSerializer(), new InnerDTOSerializer()]
+        );
+
+        serializationService = bundle.serializationService;
+
+        const mainDTO = createMainDTO();
+        await expect(serialize(
```
Comment (srknzl) [inline test/unit/serialization/compact/CompactTest.js:258]: Can you assert the exception message contains "No serializer is registered" (or similar) here? 

So you can use any string that will make sure newly added error is thrown. A random `HazelcastSerializationError` thrown will make this test pass.

**Review by srknzl — CHANGES_REQUESTED** [review]
some comments left.

File: test/integration/backward_compatible/parallel/serialization/compact/CompactUtil.js (hunk 2 above)
Comment (mehmettokgoz) [reply test/integration/backward_compatible/parallel/serialization/compact/CompactUtil.js:1491]: When we don't catch this error it continuously executes the same function (see line [1493](https://github.com/hazelcast/hazelcast-nodejs-client/pull/1365/files#diff-d952c81eb5a44c38d522d83728d20c98c52e1bf57f9c2af12793dcbfafffa717R1493)) until out of memory. We are using this function only for testing purposes.

File: src/serialization/compact/CompactStreamSerializer.ts (hunk 1 above)
Comment (mehmettokgoz) [reply src/serialization/compact/CompactStreamSerializer.ts]: Fixed at https://github.com/hazelcast/hazelcast-nodejs-client/pull/1365/commits/3345e5697bb3247845774bd13ae536ebe3124fc2.

File: test/unit/serialization/compact/CompactTest.js (hunk 3 above)
Comment (mehmettokgoz) [reply test/unit/serialization/compact/CompactTest.js]: Fixed at https://github.com/hazelcast/hazelcast-nodejs-client/pull/1365/commits/3345e5697bb3247845774bd13ae536ebe3124fc2.

File: test/unit/serialization/compact/CompactTest.js (hunk 4 above)
Comment (mehmettokgoz) [reply test/unit/serialization/compact/CompactTest.js:258]: Fixed at https://github.com/hazelcast/hazelcast-nodejs-client/pull/1365/commits/3345e5697bb3247845774bd13ae536ebe3124fc2.

File: test/integration/backward_compatible/parallel/serialization/compact/CompactUtil.js (hunk 2 above)
Comment (srknzl) [reply test/integration/backward_compatible/parallel/serialization/compact/CompactUtil.js:1491]: Ok makes sense. Then we can change the logic a little bit to be as follows.

```js
try {
      return serializationService.toData(obj);
} catch (e) {
    if (e instanceof SchemaNotReplicatedError) {
        await schemaService.put(e.schema);  
        return serialize(serializationService, schemaService, obj);
    }
    throw e;
}
```

Note that `await` is not needed in while returning recursively. It was unnecessary.

Comment (mehmettokgoz) [reply test/integration/backward_compatible/parallel/serialization/compact/CompactUtil.js]: Refactored at https://github.com/hazelcast/hazelcast-nodejs-client/pull/1365/commits/1d60244de304441b291ab50d5177b263bfc11107.

File: test/unit/serialization/compact/CompactTest.js [hunk 5]
```diff
@@ -244,4 +246,19 @@ describe('CompactTest', function () {
...
+            serializationService,
+            bundle.schemaService,
+            mainDTO)).to.be.eventually.rejectedWith(HazelcastSerializationError).and.have.property('message',
+            'No serializer is registered for class/constructor NamedDTO.');
```
Comment (srknzl) [inline test/unit/serialization/compact/CompactTest.js:262]:
```suggestion
            'No serializer is registered for class/constructor.');
```

An optional suggestion to save this test from failing when NamedDTO is renamed. Asserting whole message makes this test very easy to fail. Asserting   `No serializer is registered for class/constructor` part is enough to make sure correct HazelcastSerializationError is thrown and not another HazelcastSerializationError that might happen due to various reasons.

**Review by srknzl — APPROVED** [review]

**Review by srknzl — APPROVED** [review]

File: test/unit/serialization/compact/CompactTest.js [hunk 6]
```diff
@@ -244,4 +247,24 @@ describe('CompactTest', function () {
...
+        );
+
+        serializationService = bundle.serializationService;
+
+        const mainDTO = createMainDTO();
+        TestUtil.getRejectionReasonOrThrow(serialize(
+            serializationService,
+            bundle.schemaService,
+            mainDTO
+        ));
```
Comment (srknzl) [inline test/unit/serialization/compact/CompactTest.js:263]:
```suggestion
```

**Review by srknzl — APPROVED** [review]
