### PR TITLE
Fix TranslateAddressProviderTest API-1111

### LINKED ISSUE #1165: TranslateAddressProviderTest failure [API-1111]
On windows and cd6240ed9569b6f8fdb9ef7339ea7e6e3beb6448
```
 1) TranslateAddressProviderTest
       should provide true for default config and publicly reachable single member:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test\unit\network\TranslateAddressProviderTest.js:236:37)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) TranslateAddressProviderTest
       should provide true for default config and publicly reachable members:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test\unit\network\TranslateAddressProviderTest.js:251:37)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

### PR DESCRIPTION
**Pull request by srknzl**
fixes #1165 

See the issue for explanation of the change. I used TEST-NETWORK-2 as mentioned [here](https://superuser.com/a/698392)

### CODE REVIEW

File: test/unit/network/TranslateAddressProviderTest.js [hunk 1]
```diff
@@ -33,7 +33,8 @@ const { UuidUtil } = require('../../../lib/util/UuidUtil');
 describe('TranslateAddressProviderTest', function () {
     const PROPERTY_DISCOVERY_PUBLIC_IP_ENABLED = 'hazelcast.discovery.public.ip.enabled';
     const REACHABLE_HOST = '127.0.0.1';
-    const UNREACHABLE_HOST = '192.168.0.1';
+    // Test network ip, should be unreachable
+    const UNREACHABLE_HOST = '198.51.100.1';
```
Comment (yuce) [inline test/unit/network/TranslateAddressProviderTest.js:37]: Could you provide a link about this IP as a comment?

**Review by yuce — APPROVED** [review]

**Review by mdumandag — APPROVED** [review]
