### PR TITLE
prevent client hanging due to incompatible server

### LINKED ISSUE #132: Client does not fail fast with incompatible server
If server does not support open binary protocol, it seems client hangs forever without giving any error. It should fail fast with a reasonable error message.

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR fixes client hanging defect that occurs when there is a server that does not support open binary protocol. It returns an `IllegalStateError` with message `Connection timed-out`.

fixes #132

### CODE REVIEW

File: test/ConnectionManagerTest.js [hunk 1]
```diff
@@ -100,5 +108,17 @@ describe('ConnectionManager', function () {
                 done(new Error('Client should be retrying!\n' + e));
             }
         });
-    })
+    });
+
+    it('should throw IllegalStateError if there is an incompatible server', function () {
```
Comment (mustafaiman) [inline test/ConnectionManagerTest.js]: Isn't this the same test as `gives up connecting after timeout`?

Comment (furkansenharputlu) [reply test/ConnectionManagerTest.js]: No, that test just checks first connection attempt and was passing. Client was hanging at the second attempt. This test checks whether client hangs or not after first attempt.

Comment (mustafaiman) [reply test/ConnectionManagerTest.js]: Nevermind, I see the difference. However, I did not like this test as it assumes a certain order of running tests. The test shutdowns the cluster that the others depend on. You can isolate the unresponsive server by starting it at a different port and having client configuration list it.

Comment (furkansenharputlu) [reply test/ConnectionManagerTest.js]: However, client will try `5701` port when it cannot connect. Therefore, I need to run the server on `5701`.

Comment (mustafaiman) [reply test/ConnectionManagerTest.js]: Why should it? If I give only a single port in config, will it try 5701 anyway? It may try but I doubt it should.

Comment (furkansenharputlu) [reply test/ConnectionManagerTest.js]: It adds here: https://github.com/hazelcast/hazelcast-nodejs-client/blob/22ecdbf996a35761c63aee0eccd72ef919160d7b/src/connection/DefaultAddressProvider.ts#L39

Comment (furkansenharputlu) [reply test/ConnectionManagerTest.js]: Actually, you are right when there is no address passed on config, it automatically tries to connect to `5071`. When I pass `127.0.0.1:9999`, it won't try to connect to `5071`.
