### PR TITLE
API-555 Fix ReliableTopicOnClusterRestart test

### LINKED ISSUE #939: ReliableTopicOnClusterRestartTest: should continue on cluster restart when data lost and after invocation timeout
Failed at http://jenkins.hazelcast.com/job/NodeJS-pr-builder/1261/testReport/junit/Node.js%20Client%20Tests/ReliableTopicOnClusterRestartTest/should_continue_on_cluster_restart_when_data_lost_and_after_invocation_timeout/

Error Message

Rejected due to timeout of 60000ms

Stacktrace
```
    at Timeout.setTimeout [as _onTimeout] (test/TestUtil.js:83:20)
Standard Çıktı (STDOUT)
[DefaultLogger] INFO at LifecycleService: HazelcastClient is STARTING
[DefaultLogger] INFO at LifecycleService: HazelcastClient is STARTED
[DefaultLogger] INFO at ConnectionManager: Trying to connect to 127.0.0.1:5701
[DefaultLogger] INFO at LifecycleService: HazelcastClient is CONNECTED
[DefaultLogger] INFO at ConnectionManager: Authenticated with server localhost:5701:8f2e7b67-78c1-4247-9f79-a62655eef5f1, server version: 4.2.1-SNAPSHOT, local address: 127.0.0.1:51866
[DefaultLogger] INFO at ClusterService: 

Members [1] {
	Member [localhost]:5701 - 8f2e7b67-78c1-4247-9f79-a62655eef5f1
}

[DefaultLogger] INFO at LifecycleService: HazelcastClient is STARTING
[DefaultLogger] INFO at LifecycleService: HazelcastClient is STARTED
[DefaultLogger] INFO at ConnectionManager: Trying to connect to 127.0.0.1:5701
[DefaultLogger] INFO at LifecycleService: HazelcastClient is CONNECTED
[DefaultLogger] INFO at ConnectionManager: Authenticated with server localhost:5701:8f2e7b67-78c1-4247-9f79-a62655eef5f1, server version: 4.2.1-SNAPSHOT, local address: 127.0.0.1:51868
[DefaultLogger] INFO at ClusterService: 

Members [1] {
	Member [localhost]:5701 - 8f2e7b67-78c1-4247-9f79-a62655eef5f1
}

[DefaultLogger] WARN at Connection: Connection{alive=false, connectionId=0, remoteAddress=localhost:5701} closed. Reason: Socket error. Connection might be closed by other side - EPIPE: This socket has been ended by the other party
[DefaultLogger] INFO at ConnectionManager: Removed connection to endpoint: localhost:5701:8f2e7b67-78c1-4247-9f79-a62655eef5f1, connection: Connection{alive=false, connectionId=0, remoteAddress=localhost:5701}
[DefaultLogger] INFO at LifecycleService: HazelcastClient is DISCONNECTED
[DefaultLogger] INFO at ConnectionManager: Trying to connect to Member [localhost]:5701 - 8f2e7b67-78c1-4247-9f79-a62655eef5f1
[DefaultLogger] WARN at ConnectionManager: Switching from current cluster: ed3571bd-8c11-4c83-ba96-5b5fd4cea05c to new cluster: 3281a92d-bd25-4f72-8fee-72c8c1ee8e6a
[DefaultLogger] INFO at HazelcastClient: Clearing local state of the client, because of a cluster restart.
[DefaultLogger] INFO at ConnectionManager: Authenticated with server localhost:5701:d3103a55-4e2a-419e-90d8-f3f311555dd1, server version: 4.2.1-SNAPSHOT, local address: 127.0.0.1:51896
[DefaultLogger] INFO at ClusterService: 

Members [1] {
	Member [localhost]:5701 - d3103a55-4e2a-419e-90d8-f3f311555dd1
}

[DefaultLogger] INFO at LifecycleService: HazelcastClient is CONNECTED
[DefaultLogger] WARN at Connection: Connection{alive=false, connectionId=0, remoteAddress=localhost:5701} closed. Reason: Socket error. Connection might be closed by other side - EPIPE: This socket has been ended by the other party
[DefaultLogger] INFO at ConnectionManager: Removed connection to endpoint: localhost:5701:8f2e7b67-78c1-4247-9f79-a62655eef5f1, connection: Connection{alive=false, connectionId=0, remoteAddress=localhost:5701}
[DefaultLogger] INFO at LifecycleService: HazelcastClient is DISCONNECTED
[DefaultLogger] INFO at ConnectionManager: Trying to connect to Member [localhost]:5701 - 8f2e7b67-78c1-4247-9f79-a62655eef5f1
[DefaultLogger] WARN at ConnectionManager: Switching from current cluster: ed3571bd-8c11-4c83-ba96-5b5fd4cea05c to new cluster: 3281a92d-bd25-4f72-8fee-72c8c1ee8e6a
[DefaultLogger] INFO at HazelcastClient: Clearing local state of the client, because of a cluster restart.
[DefaultLogger] INFO at ConnectionManager: Authenticated with server localhost:5701:d3103a55-4e2a-419e-90d8-f3f311555dd1, server version: 4.2.1-SNAPSHOT, local address: 127.0.0.1:51928
[DefaultLogger] INFO at LifecycleService: HazelcastClient is CONNECTED
[DefaultLogger] INFO at ClusterService: 

Members [1] {
	Member [localhost]:5701 - d3103a55-4e2a-419e-90d8-f3f311555dd1
}

[DefaultLogger] WARN at ReliableTopicProxy: Failed to fetch sequence for runner.
{ Error: Invocation 6) reached its deadline.
    at new OperationTimeoutError (/home/jenkins/jenkins_slave/workspace/NodeJS-pr-builder/lib/core/HazelcastError.js:22:2447)
    at InvocationService.rejectIfNotRetryable (/home/jenkins/jenkins_slave/workspace/NodeJS-pr-builder/lib/invocation/InvocationService.js:60:829)
    at InvocationService.notifyError (/home/jenkins/jenkins_slave/workspace/NodeJS-pr-builder/lib/invocation/InvocationService.js:53:6766)
    at Timeout.Util_1.scheduleWithRepetition [as _onTimeout] (/home/jenkins/jenkins_slave/workspace/NodeJS-pr-builder/lib/invocation/InvocationService.js:35:2740)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  cause:
   { Error: Socket error. Connection might be closed by other side
       at new TargetDisconnectedError (/home/jenkins/jenkins_slave/workspace/NodeJS-pr-builder/lib/core/HazelcastError.js:22:8927)
       at Timeout.Util_1.scheduleWithRepetition [as _onTimeout] (/home/jenkins/jenkins_slave/workspace/NodeJS-pr-builder/lib/invocation/InvocationService.js:35:2763)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10) cause: undefined, serverStackTrace: undefined },
  serverStackTrace: undefined }
```

### PR DESCRIPTION
**Pull request by srknzl**
I realized in Github actions addMessageListener's `tailSequence` call may not be completed before shutting down the member. This leads to uninitialized message listener, therefore an error:  'Failed to fetch sequence for runner.'.

To fix this we should wait some time for the message listener to be initialized before shutting down the member. 

Also adds 4.0.2 min version since there was a fix on 4.0.2  https://github.com/hazelcast/hazelcast-nodejs-client/pull/704

green gh runs for 4.1.0, 4.2.0, 4.0.2 and os, enterprise combinations:

https://github.com/srknzl/test/runs/2898723299
https://github.com/srknzl/test/runs/2898838318
https://github.com/srknzl/test/runs/2898840470
https://github.com/srknzl/test/runs/2898842130
https://github.com/srknzl/test/runs/2898932621
https://github.com/srknzl/test/runs/2898931833

fixes #939

### CODE REVIEW

File: test/integration/backward_compatible/topic/ReliableTopicOnClusterRestart.js [hunk 1]
```diff
@@ -29,6 +29,10 @@ describe('ReliableTopicOnClusterRestartTest', function () {
     let client1;
     let client2;
 
+    before(function () {
+        markClientVersionAtLeast(this, '4.0.2');
```
Comment (mdumandag) [inline test/integration/backward_compatible/topic/ReliableTopicOnClusterRestart.js:33]: Maybe we can add the link of the PR here as a comment to make the life of the future-readers easier

File: test/integration/backward_compatible/topic/ReliableTopicOnClusterRestart.js [hunk 2]
```diff
@@ -92,6 +96,9 @@ describe('ReliableTopicOnClusterRestartTest', function () {
             messageArrived = true;
         });
 
+        // wait some time for message listener to initialized
+        await promiseWaitMilliseconds(2000);
```
Comment (mdumandag) [inline test/integration/backward_compatible/topic/ReliableTopicOnClusterRestart.js:100]: I don't like this kind of fixed-duration sleeps because they are prone to failures.

Can we try to do something else, like spy the `ReliableTopicListenerRunner` and wait until the `runner.next()` is called via assertTrueEventually?

**Comment by srknzl** [comment]
Ran the tests again check last 6 runs in https://github.com/srknzl/test/actions/workflows/server_compatibility.yaml

File: test/integration/backward_compatible/topic/ReliableTopicOnClusterRestart.js [hunk 3]
```diff
@@ -92,6 +101,13 @@ describe('ReliableTopicOnClusterRestartTest', function () {
             messageArrived = true;
         });
 
+        // wait for the message listener to be initialized
+        const runner = Object.values(topic1.runners)[0];
+        const nextFake = sandbox.replace(runner, 'next', sandbox.fake(runner.next));
+        await assertTrueEventually(async () => {
+            nextFake.called.should.be.true;
```
Comment (srknzl) [inline test/integration/backward_compatible/topic/ReliableTopicOnClusterRestart.js:108]: see `Using fakes instead of spies` section in https://sinonjs.org/releases/v11.1.1/fakes/ for more about this usage

**Review by mdumandag — APPROVED** [review]

**Comment by mdumandag** [comment]
verify
