### PR TITLE
Fix ReliableTopic implementation

### LINKED ISSUE #543: Fix ReliableTopic implementation
In IMDG 4.0, server does not throw `StaleSequenceError` [anymore](https://github.com/hazelcast/hazelcast/pull/16303). We need to update our implementation accordingly and re-activate `Reliable Topic Proxy#continues operating when stale sequence is reached` test.

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Closes: #543
Refs: #569

* Removes `StaleSequenceError` handling from `ReliableTopicListenerRunner`
* Adds timeout error handling into `ReliableTopicListenerRunner`
* Renames test scripts for Reliable Topic and Ringbuffer
* Migrates tests for Reliable Topic and Ringbuffer to async/await syntax
* Also adds new tests for Reliable Topic and Ringbuffer 

I've created #566 as a side effect of investigating this issue.

### CODE REVIEW

File: src/proxy/topic/ReliableTopicListenerRunner.ts [hunk 1]
```diff
@@ -59,45 +59,55 @@ export class ReliableTopicListenerRunner<E> {
...
     public cancel(): void {
         this.cancelled = true;
     }
 
+    private scheduleNext(): void {
+        setImmediate(this.next.bind(this));
+    }
+
+    private handleInternalError(err: Error): boolean {
+        if (err instanceof InvocationTimeoutError) {
```
Comment (mdumandag) [inline src/proxy/topic/ReliableTopicListenerRunner.ts:105]: There was an issue reported to the main repo. https://github.com/hazelcast/hazelcast/issues/17070

Maybe we could also handle `ClientNotActiveError` and log it in `trace` level instead of `warn`.

File: test/topic/ReliableTopicTest.js [hunk 2]
```diff
@@ -130,97 +121,73 @@ describe('TopicTest', function () {
...
+        const ringbuffer =  topic.getRingbuffer();
+
+        const all = generateItems(clientOne, 10);
+        await ringbuffer.addAll(all);
+        await topic.publish(11);
+
+        const seq = await ringbuffer.tailSequence();
+        const item = await ringbuffer.readOne(seq);
+        const obj = clientOne.getSerializationService().toObject(item.payload);
+        expect(obj).to.equal(11);
```
Comment (mdumandag) [inline test/topic/ReliableTopicTest.js:191]: Not related to this PR, but do we have an issue about migrating tests to `async/await`? It is a lot readable :smile:

File: src/proxy/topic/ReliableTopicListenerRunner.ts [hunk 3]
```diff
@@ -59,45 +59,55 @@ export class ReliableTopicListenerRunner<E> {
...
-                        this.sequenceNumber = newSequence;
-                        setImmediate(this.next.bind(this));
-                    });
 
-                    return;
+                const nextSeq = result.getNextSequenceToReadFrom().toNumber();
+                const lostCount = nextSeq - result.getReadCount() - this.sequenceNumber;
+                if (lostCount !== 0) {
+                    this.logger.trace('ReliableTopicListenerRunner', 'Listener of topic: ' + this.proxy.getName()
+                        + ' lost ' + lostCount + ' messages');
```
[the remark this answers is not in the document]
Comment (puzpuzpuz) [reply src/proxy/topic/ReliableTopicListenerRunner.ts]: Good catch. Changed the logic in 9d6b40d274bcbaf29f9d05a40009bdf2c807736b

File: src/proxy/topic/ReliableTopicListenerRunner.ts (hunk 1 above)
Comment (puzpuzpuz) [reply src/proxy/topic/ReliableTopicListenerRunner.ts:111]: Thanks for the heads-up. Changed the error logging in 9d6b40d274bcbaf29f9d05a40009bdf2c807736b

File: test/topic/ReliableTopicTest.js (hunk 2 above)
Comment (puzpuzpuz) [reply test/topic/ReliableTopicTest.js:191]: Yeah, it's a lot more readable. I was going to migrate tests incrementally as a part of other PRs. But having this plan defined as a GH issue is a good idea. Going to create one.

Comment (puzpuzpuz) [reply test/topic/ReliableTopicTest.js:191]: Here it goes: #569

**Comment by puzpuzpuz** [comment]
@mdumandag I've addressed pending comments. Could you take another look?

File: src/proxy/topic/ReliableTopicListenerRunner.ts [hunk 4]
```diff
@@ -65,9 +69,13 @@ export class ReliableTopicListenerRunner<E> {
 
                 const nextSeq = result.getNextSequenceToReadFrom().toNumber();
                 const lostCount = nextSeq - result.getReadCount() - this.sequenceNumber;
+                // If messages were lost, behave as a non-loss tolerant listener
                 if (lostCount !== 0) {
-                    this.logger.trace('ReliableTopicListenerRunner', 'Listener of topic: ' + this.proxy.getName()
-                        + ' lost ' + lostCount + ' messages');
+                    this.logger.warn('ReliableTopicListenerRunner', 'Terminating listener of topic: '
+                        + this.proxy.getName() + '. Reason: The listener was too slow lost or the retention'
```
Comment (mdumandag) [inline src/proxy/topic/ReliableTopicListenerRunner.ts:75]: Minor: `Reason: The listener was too slow lost or the retention...` should be `Reason: The listener was too slow or the retention...` (extra `lost`)

Comment (puzpuzpuz) [reply src/proxy/topic/ReliableTopicListenerRunner.ts]: Fixed in ab19d9c259760e62bccbcb020cf913f3e78572f8

**Comment by puzpuzpuz** [comment]
@mdumandag thanks for the quick review!

File: src/proxy/topic/ReliableTopicListenerRunner.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (puzpuzpuz) [reply src/proxy/topic/ReliableTopicListenerRunner.ts]: I'd like to reiterate on this one.

The previous implementation was handling `StaleSequenceError` as if it was based on a loss tolerant listener. I think we should do the same here. Otherwise we leave users sitting on a time bomb. If producers have a spike in message generation for a single time, the listener will be terminated and users will have no programmatic way to handle the termination and, say, register another listener. I have reverted the logic in cdcf57cfd71c9dc77ee9f9639be046f740d3b04e

WDYT?

Off-topic: I have also removed redundant `setImmediate` from `ReliableTopicListenerRunner`. See: 56a37ca07bf7a3f66474bd137c22b9239b63c565

[the remark this answers is not in the document]
Comment (mdumandag) [reply src/proxy/topic/ReliableTopicListenerRunner.ts]: Hmm, okay, that makes sense. With a `warn` level log, I guess, it should be okay.
