### PR TITLE
Fix flaky HazelcastClientTest API-1194 [4.0.x]

### LINKED ISSUE #1173: getDistributedObjects - "getDistributedObjects does not return removed object" failure  [API-1194]
Failed on Node 10 and 17, on windows with commit https://github.com/hazelcast/hazelcast-nodejs-client/commit/e6956513c7e97995cf997172cf6a5ab15be8cd87

```
1) HazelcastClientTest[smart=false]
       getDistributedObjects does not return removed object:
     Error: Rejected due to timeout of 5000ms
      at Timeout.setTimeout (test\TestUtil.js:86:20)
```

### PR DESCRIPTION
**Pull request by srknzl**
Fixes the possible flakiness of the test and makes the test cleaner. 

fixes #1173

### CODE REVIEW

**Review by mdumandag — APPROVED** [review]

File: test/HazelcastClientTest.js [hunk 1]
```diff
@@ -19,27 +19,25 @@ const expect = require('chai').expect;
...
     async destroyAll() {
         const promises = [];
         this.managedObjects.forEach(function (obj) {
             promises.push(obj.destroy());
         });
         return Promise.all(promises);
-    };
+    }
 
     destroy(name) {
```
[the remark this answers is not in the document]
Comment (srknzl) [reply test/HazelcastClientTest.js]: You are right, backported that as well

**Review by mdumandag — DISMISSED** [review]

File: test/HazelcastClientTest.js [hunk 2]
```diff
@@ -82,30 +57,31 @@ configParams.forEach(function (cfg) {
         before(async function () {
             cluster = await RC.createCluster(null, null);
             await RC.startMember(cluster.id);
-            cfg.clusterName = cluster.id;
-            client = await Client.newHazelcastClient(cfg);
+            client = await Client.newHazelcastClient({
```
Comment (mdumandag) [inline test/HazelcastClientTest.js:60]: BTW, we are creating the client in beforeEach in 5.x series. It might also be better here for test isolation as getDistributedObjects interacts with the proxy manager

Comment (srknzl) [reply test/HazelcastClientTest.js:64]: Ok I will change all of them to be like that.

**Review by mdumandag — APPROVED** [review]

**Review by yuce — APPROVED** [review]
