### PR TITLE
Increase timeouts in MapProxyTest [4.2.x] API-1200

### LINKED ISSUE #724: Flaky MapProxyTest [API-1200]
http://jenkins.hazelcast.com/job/NodeJS-12-master/93/testReport/junit/(root)/putTransient_withTTL/MapProxyTest_Near_Cache__true_putTransient_withTTL/

```
putTransient_withTTL.MapProxyTest Near Cache: true putTransient_withTTL (from Near Cache_ true)

Error Message
expected null to equal 'val10'
Stacktrace
AssertionError: expected null to equal 'val10'
    at Context.<anonymous> (test/map/MapProxyTest.js:325:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### PR DESCRIPTION
**Pull request by srknzl**
Increased the timeouts that we increased through https://github.com/hazelcast/hazelcast-nodejs-client/pull/725 and https://github.com/hazelcast/hazelcast-nodejs-client/pull/1104

The test did not fail in master for a long time we must ensure the same happens in maintenance branches too. Increases ttls to 20 seconds because according to Yuce and Sancar in go and java 20 seconds is used.

fixes #724

### CODE REVIEW

File: test/integration/backward_compatible/map/MapProxyTest.js [hunk 1]
```diff
@@ -110,31 +110,31 @@ describe('MapProxyTest', function () {
             });
 
             it('put with ttl removes value after ttl', async function () {
-                await map.put('key10', 'val10', 1000);
+                await map.put('key10', 'val10', 2000);
```
Comment (yuce) [inline test/integration/backward_compatible/map/MapProxyTest.js:113]: I think the TTL here is too low. It's 20 seconds in the Go client. Similar for other related code in this PR.

Comment (srknzl) [reply test/integration/backward_compatible/map/MapProxyTest.js:113]: 2 seconds did not cause a problem in master for a very long time. Increasing this will lead to longer tests. What about increasing again if a fail happens?

Comment (srknzl) [reply test/integration/backward_compatible/map/MapProxyTest.js]: I have made tts 20 in all backports and opened a new pr for master.

**Review by yuce — DISMISSED** [review]

**Review by mdumandag — APPROVED** [review]

**Review by yuce — APPROVED** [review]
